### ISSUE TITLE
pub get failed

### ISSUE THREAD

**Issue by codeXLinkX** [knezzz/RandomColor#1]
[theapp] flutter packages get
Running "flutter packages get" in theapp...                     
Because every version of flutter_test from sdk depends on test 1.3.0 and every version of random_color depends on test ^1.3.4, flutter_test from sdk is incompatible with random_color.
So, because theapp depends on both random_color ^1.0.0 and flutter_test any from sdk, version solving failed.

pub get failed (1)
exit code 1

**Comment by knezzz** [comment]
Fixed :)

**Comment by codeXLinkX** [comment]
Ok great!
