### ISSUE TITLE
Support null safety

### ISSUE THREAD

**Issue by IchordeDionysos** [knezzz/RandomColor#11]
This is a request to add support for [null safety](https://dart.dev/null-safety) to `package:random_color`.
We depend on your awesome package, so would be great to have null safety enabled.

The Dart/Flutter team already encourages publishing the migrated packages: See [this blog post](https://medium.com/dartlang/preparing-the-dart-and-flutter-ecosystem-for-null-safety-e550ce72c010).

See the [migration guide](https://dart.dev/null-safety/migration-guide) for details about enabling null safety.

**Comment by knezzz** [comment]
Okay, Ill check out what I need to do to update the package to null safety :D

**Comment by IchordeDionysos** [comment]
@knezzz thanks really appreciate it 😍 

I suppose migration will be very quick, especially with the migration tool provided by the Dart team 💪

**Comment by knezzz** [comment]
Published in `1.0.6-nullsafety`

**Comment by Sheharyar566** [comment]
Any progress on this?
