### ISSUE TITLE
Error: Cannot run with sound null safety, because the following dependencies don't support null safety:

### ISSUE THREAD

**Issue by nawzhin95** [knezzz/RandomColor#15]
Hello i am trying to user this package but when i install dependicy then run the app it will show me this error as red line : ( 

Plz update

Error: Cannot run with sound null safety, because the following dependencies
don't support null safety:

**Comment by knezzz** [comment]
Hey @nawzhin95.
You can use null safe version: `1.0.6-nullsafety`. Then everything should work.

**Comment by nawzhin95** [comment]
thanks @knezzz 
everything work fine
