### ISSUE TITLE
[Feature Request] Random Material Colors list

### ISSUE THREAD

**Issue by GensaGames** [knezzz/RandomColor#6]
Just a feature request, might be for future. Random Material Colors list. Since it might be also useful,

Thanks,

**Comment by knezzz** [comment]
Sure :) Will see about it in next few days then possibly update it

**Comment by knezzz** [comment]
@GensaGames In case you need this now I added it to branch: add_random_material_color

Once I clean up the code a bit I'll update the lib :)

**Comment by GensaGames** [comment]
Thank you, 

Great job!

**Comment by knezzz** [comment]
Published in 1.0.5
